drop table if exists todo_domain CASCADE;
drop table if exists todo_system_domain CASCADE; 
create table todo_domain (id bigint generated by default as identity, date date not null, description varchar(255) not null, done boolean not null, title varchar(255) not null, the_todo_id bigint, primary key (id));
create table todo_system_domain (id bigint generated by default as identity, objective varchar(255) not null, primary key (id));
alter table todo_domain add constraint FK5c1ouw2ni3wv47ctgug4eemsh foreign key (the_todo_id) references todo_system_domain on delete cascade;